---
title: "Kaplan Table"
output: 
  flexdashboard::flex_dashboard:
 
      orientation: rows
     
 
---

```{r global, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(summarywidget)
 
library(DT)
library(htmltools)
library(htmlwidgets)
library(readr)
Collectify_6182020 <- read_csv("Collectify_6182020.csv",  na = "empty",
    col_types = cols(`Column Type` = col_factor(levels = c("Advertising Objects", 
        "Art", "Books", "Documents", "Militaria", 
        "Miscellaneous", "Monetary", "Photography", 
        "Playing Cards", "Trade And Business Cards")), 
        Language = col_factor(levels = c("Dutch", 
            "English", "English | Aramaic", 
            "English | French", "English | German", 
            "English | Latin | German", "English | Yiddish", 
            "German", "German | Yiddish | English", 
            "Hebrew", "Hebrew | Aramaic", 
            "Hebrew | Dutch", "Hebrew | English", 
            "Italian", "Spanish")), OBJECTS_DATE = col_date(format = "%m/%d/%Y"), 
        `In Colenda?` = col_factor(levels = c("Yes", 
            "Matched Manually", "No"))))

 Collectify_6182020$`Link to Colenda` <-   (paste0("<a target=_blank href='", Collectify_6182020$`Link to Colenda`,"'>", Collectify_6182020$`Link to Colenda`,"</a>") )
 
```

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r }
 sd <- SharedData$new(Collectify_6182020)
bscols(
  list(
     filter_slider(
     
   id = "OBJECTS_DATE",
   label = "Date",
   sharedData =  sd,
   column = ~`OBJECTS_DATE`,
   width = "100%"), 
     filter_select(
   id = "Column Type", 
   label = "Type",
   sharedData =  sd,
   group = ~`Column Type`)
 
  )
)




   
  
 
```


Row
-------------------------------------

### Table

```{r}

sd %>% 
  DT::datatable( 
     escape = 7,
    style = 'bootstrap',
    filter = "top",
    options = list(
      pageLength = 5,
      deferRender = TRUE,
      colReorder = TRUE,
      highlightSearch = TRUE, 
      columnDefs = list(list(
        targets = c(1:6, 8:11, 16:18), 
        visible = FALSE)), 
      buttons = c('colvis', 'excel' ), dom = 'Blfrtip'), 
  extensions = c('Buttons', 'ColReorder'),
 
  
      
 
    
      
  
    colnames = c(
      "Column Type" = "Column Type",
      "OBJECTS_OBJTYPE" = "OBJECTS_OBJTYPE",
      "OBJECTS_REFNO" = "OBJECTS_REFNO",
      "THING_UUID" = "THING_UUID",
      "Duplicates" = "Duplicates",
      "Ark" = "Ark",
      "Link to Colenda" = "Link to Colenda",
      "Colenda Date" = "Date",
      "Colenda Description" = "Description",
      "Language" = "Language",
      "OBJECTS_CANCEL" = "OBJECTS_CANCEL",
      "Description" = "OBJECTS_DESCRIPTION",
      "Date" = "OBJECTS_DATE",
      "Location" = "OBJECTS_Location",
      "Person(s)" = "OBJECTS_Person",
      "Cross Reference Number" = "OBJECTS_CrossRef",
      "Physically Located?" = "Physically Located?",
      "In Colenda?" = "In Colenda?"
    )

    )
  

```
